const express = require('express')
const router = express.Router()
const salesforceService = require('../services/salesforceService')
const salesforceMService = require('../services/salesforceMService')
router.get('/login', salesforceService.login)
router.get('/callback', salesforceService.callback)
router.post('/api/lead/create', salesforceService.leadCreation)
router.post('/api/user/login', salesforceService.loginUser)
router.get('/api/:userName', salesforceService.dashboardDetails)
router.post('/api/loanApplication/create', salesforceService.loanApplication)
router.get('/mllogin', salesforceMService.mllogin)
router.get('/mlcallback', salesforceMService.mlcallback)
router.post('/api/panAuth',salesforceMService.panAuth)
router.post('/api/panStatus',salesforceMService.panStatus)
router.post('/api/panProfile',salesforceMService.panProfile)
// router.get('/api/ETB/:pan',salesforceService.checkETB)
router.post('/api/ETB/', salesforceService.checkETB)
module.exports = router